# Generated by Django 2.2.4 on 2019-08-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sub_renewal_date',
            field=models.DateField(editable=False, null=True, verbose_name='renewal date'),
        ),
    ]
