# Generated by Django 2.2.4 on 2019-08-13 10:51

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20190812_2025'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('plans', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='sub_renewal_date',
            field=models.DateField(null=True, verbose_name='renewal date'),
        ),
        migrations.AlterUniqueTogether(
            name='website',
            unique_together={('id', 'url')},
        ),
    ]
