# Generated by Django 2.2.4 on 2019-08-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20190813_1051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('id', 'plan_type')},
        ),
    ]
