# Generated by Django 2.2.4 on 2019-08-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20190813_1051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='website',
            unique_together=set(),
        ),
    ]
