# Generated by Django 2.2.4 on 2019-08-13 17:25

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_auto_20190813_1645'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('single', 'single'), ('plus', 'plus'), ('infinite', 'unlimited')], default='single', max_length=60, verbose_name='plan type'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='total_websites_allowed',
            field=models.IntegerField(default=1, help_text='For unlimited plans, 0 is inserted', verbose_name='websites allowed'),
        ),
    ]
