# Generated by Django 2.2.4 on 2019-08-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_auto_20190813_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sub_renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='renewal date'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='total_websites_allowed',
            field=models.PositiveIntegerField(default=1, help_text='For unlimited plans, 0 is inserted', verbose_name='websites allowed'),
        ),
    ]
